### PR TITLE
Blaise_portfolio

### PR DESCRIPTION
**Pull request by shiminyiblaise**
In project the following was implemented;
I cloned the repository
I created some folders and files only for linters installation
setup and installed linters to enhanced coding standard 
created a file for index.html and style.css
Then push to github following git's standard

### CODE REVIEW

**Review by ngalamac — COMMENTED** [review]
Hi @shiminyiblaise  

#  Status: Invalidated :red_circle: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project that doesnt display linter checks, please kindliy fix that and resubmit when done

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by ngalamac — APPROVED** [review]
# STATUS: APPROVED :green_circle: :clap: 
## Hi @shiminyiblaise   🙋‍♂️, 

Your project is complete!  There is nothing else to say other than... Great job 👏 

approved-accepted

Congratulations! 🎉 
TO HIGHLIGHT:

- Followed instructions 
- ✔️ Linters passing
- ✔️ Correct GitHub Flow
- ✔️ Descriptive Pull Request
- ✔️ Professional README file

Now you can merge this branch and move on :1st_place_medal: 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](#)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](#)._

HAPPY CODING AND GOOD LUCK WITH THE COMING ONES :crossed_fingers: :four_leaf_clover:

**Review by JoshuaNK0 — CHANGES_REQUESTED** [review]
### **Status: Changes Required**
Hi @shiminyiblaise 
Great job so far but I noticed you have some areas within your project that need changes

### Highlights
✔️ Linters passing 
✔️ Correct Github flows
✔️ Descriptive Pull request

### Changes Required ♻️ 

- Please edit the font color of your texts to replicate that of the project
- Enlarge the sizes of your buttons
- Edit this section of your code to remove the image icon https://github.com/shiminyiblaise/BLAISE_portfolio_website/blob/3add3ff502a8f3ebec2b405c7698237ce2d1c6f4/index.html#L61
- Style the lists(li) of your about section to give it the stipulated color from the design
 
Feel free to leave any questions or comments in the PR section if you didn't get clarity on anything

Cheers and happy coding 👏 👏 👏

**Review by ngalamac — APPROVED** [review]
Hi @shiminyiblaise @JoshuaNK0  

Your project is complete!  There is nothing else to say other than it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights
✅ Followed the best practices in code review
✅ Used interactive emojis
✅ The review is top-notch! 💯

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table  width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Ngala Mac</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/ngalamac">
        GitHub
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com">
        LinkedIn
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        Slack
      </a>
    </td>
    <td align="center">
      <a href="mailto:macngala4@gmail.com">
        Email
      </a>
    </td>
  </tr>
</table>

------
_As described in the [Code reviews limits policy](#)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](#)._

**Pull request merged**
